---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cyclone"
  labels:
    name: "cyclone"
  namespace: "default"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cyclone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: "cyclone"
      labels:
        name: "cyclone"
    spec:
      containers:
        - name: "cyclone"
          image: "public.ecr.aws/c6j6a0e2/biparjoy:7bc16fbbcb288e32936892f2034dec490bad72e0"
          imagePullPolicy: Always
          
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 256Mi
---

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "app-cyclone"
  labels:
    name: "app-cyclone"
  namespace: "default"
spec:
  type: "LoadBalancer"
  selector:
    name: "cyclone"
  ports:
    - name: "http"
      port: 80
      targetPort: 8088
      protocol: "TCP"

---
