---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cyclone"
  labels:
    name: "cyclone"
  namespace: "default"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cyclone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: "cyclone"
      labels:
        name: "cyclone"
    spec:
      containers:
        - name: "cyclone"
          image: "public.ecr.aws/c6j6a0e2/biparjoy:5151935ee54b64dc568ab17581e4df7e80c2700b"
          imagePullPolicy: Always
          
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 256Mi
           ports:
             - containerPort: 80
---

---
apiVersion: v1
kind: Service
metadata:
  name: cyclone
  labels:
    name: cyclone
  namespace: default
spec:
  type: LoadBalancer
  selector:
    name: cyclone
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

---

---
apiVersion: v1
kind: Service
metadata:
  name: app-cyclone
  labels:
    name: app-cyclone
  namespace: default
spec:
  type: NodePort
  selector:
    name: cyclone
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30000

---
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: cyclone
#   annotations:
#     kubernetes.io/ingress.class: albv2
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/healthcheck-path: /healthz
#     alb.ingress.kubernetes.io/target-type: instance
#     #alb.ingress.kubernetes.io/subnets: subnet-0f24cd94c0ed5d79c,subnet-0c558de5f8aa0131c
#     #alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:645214606845:certificate/0269e7e7-4f02-415e-b22f-56eb250c3535
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
#     alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: ssl-redirect
#                 port:
#                   name: use-annotation
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: cyclone
#                 port:
#                   number: 80
# ---
