---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cyclone"
  labels:
    name: "cyclone"
  namespace: "default"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cyclone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: "cyclone"
      labels:
        name: "cyclone"
    spec:
      containers:
        - name: "cyclone"
          image: "public.ecr.aws/c6j6a0e2/biparjoy:cb3c3fa51ee16f3a2ede9b231f4c1b855529d604"
          imagePullPolicy: Always
          
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 80
---
---
apiVersion: v1
kind: Service
metadata:
  name: "app-cyclone"
  labels:
    name: "app-cyclone"
  namespace: default
spec:
  type: NodePort
  selector:
    name: "cyclone"
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30000

---
apiVersion: v1
kind: Service
metadata:
  name: "cyclone1"
  labels:
    name: "cyclone1"
  namespace: default
spec:
  type: LoadBalancer
  selector:
    name: "cyclone"
  ports:
    - name: http
      port: 80
      targetPort: 80
---
