apiVersion: k8s.humalecttest.io/v1
kind: ApplicationGroup
metadata:
  name: eathquake-application-group
spec:
  applications:
    - name: app-eathquake
      domain: example.com
      replicas: 1
      # Additional application-specific configuration
    - name: app-ankit
      domain: example.com
      replicas: 1
      # Additional application-specific configuration
    # Add more applications as needed

