name: Run Ansible

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Replace with your desired Python version

      - name: Install Ansible
        run: pip install ansible

      - name: Run Ansible playbook
        # env:
        #   PARAMETER_NAME: ${{ secrets.PARAMETER_NAME }} # Replace with your parameter name
        ls
        run: ansible-playbook -i /biparjoy/dotnet-install-role/inventory_lnrc /biparjoy/dotnet-install-role/main.yml
